name: Docker Image CI for GHCR

on: 
  push:
      paths-ignore:
      - 'README.md'

jobs:
  build_publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: |
          docker login --username Spectre7651 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
      - name: Build Image
        run: |
          docker build . --tag ghcr.io/spectre7651/blueprint-cloudforest:latest
      - name: Push to GCHR
        run: |
          docker push ghcr.io/spectre7651/blueprint-cloudforest:latest
      - name: Send a discord note
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: Hey DockerCI succeeded in ${{ github.repository}}
