name: Docker Image CI for GHCR

on: 
  push

jobs:
  build_publish:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: |
          docker login --username Spectre7651 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
      - name: Build Image
        run: |
          docker build . --tag ghcr.io/spectre7651/blueprint-cloudforest:latest --platform linux/arm64
      - name: Push to GCHR
        run: |
          docker push ghcr.io/spectre7651/blueprint-cloudforest:latest
